# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
broadcast = "broadcast"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999

bytecode_hash = 'none'
ast = true
gas_limit = 9223372036854775807
ffi = true
evm_version = "cancun"

fs_permissions = [
    { access='read', path='./deploy-config/' },
    { access='read', path='./test/nitro-attestation/' },
    { access='read-write', path='./deployments/' },
    { access='read', path = './out/' }
]
